version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
    volumes:
      - ./nats-conf/nats-server.conf:/nats-server.conf
    command: ["-c","/nats-server.conf"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./customPostgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  dataprovider:
    depends_on:
      - nats
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ALPACA_KEY=${ALPACA_KEY}
      - ALPACA_SECRET=${ALPACA_SECRET}
    command:
      - "/app/component"
      - "-n"
      - "${NATS_URL}"
  datastorage:
    depends_on:
      - nats
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COMPONENT=datastorage
    command:
      - "/app/component"
      - "-d"
      - "host=db port=5432 user=postgres password=example dbname=opentradingplatform sslmode=disable"
      - "-c"
      - "./data_storage_startup_subscription.json"
      - "-n"
      - "${NATS_URL}"
    
  sentimentanalyzer:
      depends_on:
        - nats
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - COMPONENT=sentimentanalyzer
      env_file:
        - .env
      command:
        - "/app/component"
        - "-n"
        - "${NATS_URL}"