// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: tradingstatus.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradingStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	StatusCode  string `protobuf:"bytes,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	StatusMsg   string `protobuf:"bytes,3,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	ReasonCode  string `protobuf:"bytes,4,opt,name=ReasonCode,proto3" json:"ReasonCode,omitempty"`
	ReasonMsg   string `protobuf:"bytes,5,opt,name=ReasonMsg,proto3" json:"ReasonMsg,omitempty"`
	Timestamp   int64  `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Tape        string `protobuf:"bytes,7,opt,name=Tape,proto3" json:"Tape,omitempty"`
	Fingerprint string `protobuf:"bytes,8,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Source      string `protobuf:"bytes,9,opt,name=Source,proto3" json:"Source,omitempty"`
	AssetClass  string `protobuf:"bytes,10,opt,name=AssetClass,proto3" json:"AssetClass,omitempty"`
}

func (x *TradingStatus) Reset() {
	*x = TradingStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingstatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingStatus) ProtoMessage() {}

func (x *TradingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tradingstatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingStatus.ProtoReflect.Descriptor instead.
func (*TradingStatus) Descriptor() ([]byte, []int) {
	return file_tradingstatus_proto_rawDescGZIP(), []int{0}
}

func (x *TradingStatus) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradingStatus) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *TradingStatus) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *TradingStatus) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *TradingStatus) GetReasonMsg() string {
	if x != nil {
		return x.ReasonMsg
	}
	return ""
}

func (x *TradingStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TradingStatus) GetTape() string {
	if x != nil {
		return x.Tape
	}
	return ""
}

func (x *TradingStatus) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *TradingStatus) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TradingStatus) GetAssetClass() string {
	if x != nil {
		return x.AssetClass
	}
	return ""
}

var File_tradingstatus_proto protoreflect.FileDescriptor

var file_tradingstatus_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0xaf, 0x02, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x4d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x61, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x46, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x73, 0x73, 0x65, 0x74, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x42, 0x0b, 0x5a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tradingstatus_proto_rawDescOnce sync.Once
	file_tradingstatus_proto_rawDescData = file_tradingstatus_proto_rawDesc
)

func file_tradingstatus_proto_rawDescGZIP() []byte {
	file_tradingstatus_proto_rawDescOnce.Do(func() {
		file_tradingstatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_tradingstatus_proto_rawDescData)
	})
	return file_tradingstatus_proto_rawDescData
}

var file_tradingstatus_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tradingstatus_proto_goTypes = []interface{}{
	(*TradingStatus)(nil), // 0: entities.TradingStatus
}
var file_tradingstatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tradingstatus_proto_init() }
func file_tradingstatus_proto_init() {
	if File_tradingstatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tradingstatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradingStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tradingstatus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tradingstatus_proto_goTypes,
		DependencyIndexes: file_tradingstatus_proto_depIdxs,
		MessageInfos:      file_tradingstatus_proto_msgTypes,
	}.Build()
	File_tradingstatus_proto = out.File
	file_tradingstatus_proto_rawDesc = nil
	file_tradingstatus_proto_goTypes = nil
	file_tradingstatus_proto_depIdxs = nil
}
