// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: shared/proto/data.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequestExternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fingerprint string   `protobuf:"bytes,1,opt,name=Fingerprint,proto3" json:"Fingerprint,omitempty"`
	Source      string   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	AssetClass  string   `protobuf:"bytes,3,opt,name=AssetClass,proto3" json:"AssetClass,omitempty"`
	Symbols     []string `protobuf:"bytes,4,rep,name=Symbols,proto3" json:"Symbols,omitempty"`
	Operation   string   `protobuf:"bytes,5,opt,name=Operation,proto3" json:"Operation,omitempty"`
	DataTypes   []string `protobuf:"bytes,6,rep,name=DataTypes,proto3" json:"DataTypes,omitempty"`
	Account     string   `protobuf:"bytes,7,opt,name=Account,proto3" json:"Account,omitempty"`
	StartTime   int64    `protobuf:"varint,8,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime     int64    `protobuf:"varint,9,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	TimeFrame   string   `protobuf:"bytes,10,opt,name=TimeFrame,proto3" json:"TimeFrame,omitempty"`
	NoConfirm   bool     `protobuf:"varint,11,opt,name=NoConfirm,proto3" json:"NoConfirm,omitempty"`
}

func (x *DataRequestExternal) Reset() {
	*x = DataRequestExternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequestExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequestExternal) ProtoMessage() {}

func (x *DataRequestExternal) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequestExternal.ProtoReflect.Descriptor instead.
func (*DataRequestExternal) Descriptor() ([]byte, []int) {
	return file_shared_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequestExternal) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *DataRequestExternal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DataRequestExternal) GetAssetClass() string {
	if x != nil {
		return x.AssetClass
	}
	return ""
}

func (x *DataRequestExternal) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *DataRequestExternal) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DataRequestExternal) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *DataRequestExternal) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DataRequestExternal) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *DataRequestExternal) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *DataRequestExternal) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

func (x *DataRequestExternal) GetNoConfirm() bool {
	if x != nil {
		return x.NoConfirm
	}
	return false
}

type DataResponseExternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err           string `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Status        string `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	ResponseTopic string `protobuf:"bytes,4,opt,name=ResponseTopic,proto3" json:"ResponseTopic,omitempty"`
}

func (x *DataResponseExternal) Reset() {
	*x = DataResponseExternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResponseExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponseExternal) ProtoMessage() {}

func (x *DataResponseExternal) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponseExternal.ProtoReflect.Descriptor instead.
func (*DataResponseExternal) Descriptor() ([]byte, []int) {
	return file_shared_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponseExternal) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *DataResponseExternal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DataResponseExternal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DataResponseExternal) GetResponseTopic() string {
	if x != nil {
		return x.ResponseTopic
	}
	return ""
}

var File_shared_proto_data_proto protoreflect.FileDescriptor

var file_shared_proto_data_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x22, 0xd3, 0x02, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x65, 0x74, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e,
	0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x4e, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x22, 0x80, 0x01, 0x0a, 0x14, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x45, 0x72, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x42, 0x16, 0x5a, 0x14,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_data_proto_rawDescOnce sync.Once
	file_shared_proto_data_proto_rawDescData = file_shared_proto_data_proto_rawDesc
)

func file_shared_proto_data_proto_rawDescGZIP() []byte {
	file_shared_proto_data_proto_rawDescOnce.Do(func() {
		file_shared_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_data_proto_rawDescData)
	})
	return file_shared_proto_data_proto_rawDescData
}

var file_shared_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_data_proto_goTypes = []interface{}{
	(*DataRequestExternal)(nil),  // 0: entities.DataRequestExternal
	(*DataResponseExternal)(nil), // 1: entities.DataResponseExternal
}
var file_shared_proto_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_data_proto_init() }
func file_shared_proto_data_proto_init() {
	if File_shared_proto_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequestExternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_proto_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResponseExternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_data_proto_goTypes,
		DependencyIndexes: file_shared_proto_data_proto_depIdxs,
		MessageInfos:      file_shared_proto_data_proto_msgTypes,
	}.Build()
	File_shared_proto_data_proto = out.File
	file_shared_proto_data_proto_rawDesc = nil
	file_shared_proto_data_proto_goTypes = nil
	file_shared_proto_data_proto_depIdxs = nil
}
