// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: shared/proto/stream.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequestExternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source     string   `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	AssetClass string   `protobuf:"bytes,2,opt,name=AssetClass,proto3" json:"AssetClass,omitempty"`
	Symbols    []string `protobuf:"bytes,3,rep,name=Symbols,proto3" json:"Symbols,omitempty"`
	Operation  string   `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
	DataTypes  []string `protobuf:"bytes,5,rep,name=DataTypes,proto3" json:"DataTypes,omitempty"`
	Account    string   `protobuf:"bytes,6,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *StreamRequestExternal) Reset() {
	*x = StreamRequestExternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_proto_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequestExternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequestExternal) ProtoMessage() {}

func (x *StreamRequestExternal) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequestExternal.ProtoReflect.Descriptor instead.
func (*StreamRequestExternal) Descriptor() ([]byte, []int) {
	return file_shared_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequestExternal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StreamRequestExternal) GetAssetClass() string {
	if x != nil {
		return x.AssetClass
	}
	return ""
}

func (x *StreamRequestExternal) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *StreamRequestExternal) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StreamRequestExternal) GetDataTypes() []string {
	if x != nil {
		return x.DataTypes
	}
	return nil
}

func (x *StreamRequestExternal) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

var File_shared_proto_stream_proto protoreflect.FileDescriptor

var file_shared_proto_stream_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_proto_stream_proto_rawDescOnce sync.Once
	file_shared_proto_stream_proto_rawDescData = file_shared_proto_stream_proto_rawDesc
)

func file_shared_proto_stream_proto_rawDescGZIP() []byte {
	file_shared_proto_stream_proto_rawDescOnce.Do(func() {
		file_shared_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_proto_stream_proto_rawDescData)
	})
	return file_shared_proto_stream_proto_rawDescData
}

var file_shared_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_proto_stream_proto_goTypes = []interface{}{
	(*StreamRequestExternal)(nil), // 0: entities.StreamRequestExternal
}
var file_shared_proto_stream_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_stream_proto_init() }
func file_shared_proto_stream_proto_init() {
	if File_shared_proto_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_proto_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequestExternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_proto_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_stream_proto_goTypes,
		DependencyIndexes: file_shared_proto_stream_proto_depIdxs,
		MessageInfos:      file_shared_proto_stream_proto_msgTypes,
	}.Build()
	File_shared_proto_stream_proto = out.File
	file_shared_proto_stream_proto_rawDesc = nil
	file_shared_proto_stream_proto_goTypes = nil
	file_shared_proto_stream_proto_depIdxs = nil
}
